package com.example.demo.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Persisted notification record for Module D.
 *
 * <p>Notifications are generated by other modules (Bookings, Maintenance) via
 * {@link com.example.demo.service.NotificationService#createNotification}.
 * They are delivered to the user through {@code GET /api/notifications}.
 */
@Entity
@Table(name = "notifications", indexes = {
    // Fast lookup of all notifications for a given user, ordered by newest first.
    @Index(name = "idx_notifications_user_id", columnList = "userId"),
    @Index(name = "idx_notifications_user_read",  columnList = "userId, isRead")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Notification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The database ID of the user this notification belongs to.
     * Stored as a plain foreign-key value rather than a JPA association to
     * keep the Notifications module loosely coupled from the Users module.
     */
    @Column(nullable = false)
    private Long userId;

    /** Human-readable notification text, e.g. "Your booking #42 was APPROVED." */
    @Column(nullable = false, length = 512)
    private String message;

    /**
     * Notification type / category.
     * Suggested values: {@code BOOKING_APPROVED}, {@code BOOKING_REJECTED},
     * {@code MAINTENANCE_UPDATE}, {@code SYSTEM}.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 64)
    private NotificationType type;

    /**
     * {@code false} until the user explicitly marks it read via
     * {@code PATCH /api/notifications/{id}/read}.
     */
    @Builder.Default
    @Column(nullable = false)
    private boolean isRead = false;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    // ── Notification type enum ─────────────────────────────────────────────

    public enum NotificationType {
        /** A room / resource booking was approved. */
        BOOKING_APPROVED,
        /** A room / resource booking was rejected. */
        BOOKING_REJECTED,
        /** A maintenance ticket status has changed. */
        MAINTENANCE_UPDATE,
        /** General or administrative system message. */
        SYSTEM
    }
}
