spring.application.name=demo
server.port=8081

# Supabase PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.jqlkewhlbjlbgqbsxedq&password=abyoEpgllbatbGyE&sslmode=require
spring.datasource.username=postgres
spring.datasource.password=abyoEpgllbatbGyE
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=700480566209-681gco8dsomja443nmlrb7sbtj6lahnb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# The secret below is the Base64 legacy secret from Supabase
app.jwt.supabase-secret=IpwvmoJA4vOGAV9MQDuqmQKIdY+tXjz2H1NQIAJ5eq1WzYNBBnrRaDcHgGygMhVsapc9i4cx3qEsQbxQGJnhOA==
app.jwt.supabase-jwks-url=https://jqlkewhlbjlbgqbsxedq.supabase.co/auth/v1/.well-known/jwks.json
app.supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxbGtld2hsYmpsYmdxYnN4ZWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNDI4MzcsImV4cCI6MjA4OTkxODgzN30.eAczHsEb2tY-d9xQYSSn2wTwhiK57Hcj9C89cn2o8xo
app.jwt.expiration-ms=86400000
